### ISSUE TITLE
Getting remove error -- async remove(item)

### ISSUE THREAD

**Issue by DevangRadadiya** [node-ci/nci-ansible-ui#21]
[Mon, 22 Jun 2020 08:03:53 GMT] [app] Load plugin "nci-projects-reloader"
/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/nci-projects-reloader/node_modules/chokidar/index.js:151
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/nci-projects-reloader/lib/index.js:4:13)

**Comment by okv** [comment]
Hi.
What version of nodejs do you use? Try to use nodejs >= 10 if you didn't yet.
Btw, the simplest and recommended way to try nci ansible ui is [docker image](https://github.com/node-ci/nci-ansible-ui#docker-image).

**Comment by DevangRadadiya** [comment]
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/leveldown/build'
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:198:13)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! build     at ChildProcess.emit (events.js:198:13)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/nci-projects-reloader/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T10_53_57_218Z-debug.log


After update getting above error.

i can't use docker so i need to install step by step

**Comment by DevangRadadiya** [comment]
I am not able to use docker so I need to install step by step.

Now getting this error.

make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/leveldown/build'
prebuild ERR! build error
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:198:13)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
prebuild ERR! not ok
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/usr/src/devang/nci-ansible-ui-quick-setup/node_modules/node-gyp/lib/build.js:262:23)
prebuild ERR! build     at ChildProcess.emit (events.js:198:13)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/nci-projects-reloader/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

------------------------------
[root@zk3 nci-ansible-ui-quick-setup]# node --version
v10.21.0
---------------------------------
[root@zk3 nci-ansible-ui-quick-setup]# npm --version
6.14.4

**Comment by okv** [comment]
There was a problem with outdated leveldown dependency. I've just fixed it. Try it again - should be ok, but don't forget to pull your cloned repository (or remove and clone it again).

**Comment by DevangRadadiya** [comment]
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/nci-projects-reloader/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 427 packages from 257 contributors and audited 429 packages in 7.157s

28 packages are looking for funding
  run `npm fund` for details

found 19 vulnerabilities (15 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by okv** [comment]
I'll do that, thanks for pointing that out.
Hope that is working for you now.
Closing the issue.
