### ISSUE TITLE
more screenshots

### ISSUE THREAD

**Issue by aioue** [node-ci/nci-ansible-ui#3]
Is it possible to have more screenshots, please?

Maybe a gif of how you would start running a particular playbook.

**Comment by okv** [comment]
I think currently [quick setup](https://github.com/node-ci/nci-ansible-ui/blob/master/README.md#quick-setting-up) is a sipmlest way to try it. It contains sample playbook.

**Comment by okv** [comment]
Now you can try it even more easily - within docker #4 
See updated [quick setup](https://github.com/node-ci/nci-ansible-ui/blob/master/README.md#quick-setting-up) section.
I'm closing the issue.
