### ISSUE TITLE
Several Questions

### ISSUE THREAD

**Issue by dzollinger** [node-ci/nci-ansible-ui#5]
So I got the UI working with the sample data but there are few things I'm having issues with and wanted to ask you.

- I need to change the IP the server starts on.  I can change it in data/config.yaml but it resets it every time it runs.  How can I make the IP change permanent.
- It doesn't look like the SCM module supports an SSH repo to pull playbooks from GitHub. For example if you change this line in data/projects/some_project/config.yaml it will not clone the repo.

repository: https://github.com/my-git/my-github-repository
repository: git@github.com:my-git/my-github-repository.git

**Comment by okv** [comment]
Hello.
1) If you are talking about docker installation then you should provide volume for data dir to have persisted data and config ([image page](https://hub.docker.com/r/jc21/nci-ansible-ui/) contains note about that).
2) scm module supports any repo supported by git cli command, but you should provide credentials (ssh keys in case of ssh) for the user from which nci-ansible-ui is running.

**Comment by dzollinger** [comment]
1. I am not using docker, what is the method to preserve data?  This is what I did to get started:
`git clone https://github.com/node-ci/nci-ansible-ui-quick-setup`
`cd nci-ansible-ui-quick-setup`
`npm install`
`node_modules/.bin/nci`

2. The user has the ssh keys needed.  If I run the git command manually from the cli for the same user it clones just fine.

**Comment by okv** [comment]
1. Oh, then it preserved by default (because it's just files on the disk).

```sh
git clone https://github.com/node-ci/nci-ansible-ui-quick-setup && \
cd nci-ansible-ui-quick-setup && \
npm install
```

edit data/config.yaml for your needs, then start the server:

```sh
 node_modules/.bin/nci
```

2. Try to provide .ssh/config with identity file for target host.
Server just spawns git cli command from current user in /bin/sh by default.
Console output on execution page contains command, stdout, stderr.

**Comment by dzollinger** [comment]
Ok I think I got everything working, thanks for the additional help!

**Comment by okv** [comment]
You are welcome.
