### ISSUE TITLE
doc update: build-essential is required as well

### ISSUE THREAD

**Issue by jmarshallpresnell** [node-ci/nci-ansible-ui#6]
Just a quick note that build-essential is also needed in the dependency list. :)

sudo apt-get install build-essential

Most probably already have it installed, but on a virgin system dedicated to this task, it's required to build.

Running Ubuntu 16.04.3 LTS

**Comment by okv** [comment]
Note added to the doc, thanks.

**Comment by okv** [comment]
closing it
